### PR TITLE
Add assets for Circuit Breaker

### PR DESCRIPTION
**Pull request by nevets963**

### CODE REVIEW

**Comment by Jamesp-design** [comment]
Hey I'm the designer that originally worked with Joost on the app icon. It looks as though the icon has changed slightly to be flatter, just wondering why that is and if there's anything I could do to help?

**Comment by nevets963** [comment]
@Jamesp-design Without question, we can use what was submitted :) We often receive app submissions where the graphics is 'roughly' what they want to use and we added some extra touches. Shall we go with what was submitted in the PR https://github.com/getumbrel/umbrel-apps/pull/394 ?

**Comment by Jamesp-design** [comment]
@nevets963 Ahh makes complete sense. I'd prefer to go with the original personally, but happy with the alternative if people disagree.

**Comment by nevets963** [comment]
@Jamesp-design The original icon is now part of this PR (https://github.com/getumbrel/umbrel-apps-gallery/pull/34/commits/560a0dcc2abb84f61e45de48ea7dd3fc60e05780) :)

**Review by aphex3k — APPROVED** [review]
Nice! I love the work here

**Pull request merged**
