### PR TITLE
Update LN Markets logos and Screenshots

### PR DESCRIPTION
**Pull request by kibotrel**
We updated our logo a while ago and never changed there.

### CODE REVIEW

**Comment by mayankchhabra** [comment]
Awesome! Thanks for updating the images and the icon, @kibotrel! Would you like us to merge this after the new LNM update goes live?

Also, have the new gallery images been compressed already? If not, would you be able to submit compressed images? You can use https://tinyjpg.com, it's free, easy and pretty lossless.

**Comment by kibotrel** [comment]
Yes, it would be great to have those merged once the new LNM Update goes live, images aren't compressed, I'll push them again later today!

**Comment by kibotrel** [comment]
Should be good now!

**Comment by mayankchhabra** [comment]
Awesome. Thanks, @kibotrel! Will keep an eye on the update.

**Pull request merged**
